export class Version {
    static VERSION = "2.8.1a-f2addfe" //SCRIPT_SPECIAL_TOKEN_REPLACE_GITVERSION
    static TIMESTAMP = "7/27/2026 12:47:41" //SCRIPT_SPECIAL_TOKEN_REPLACE_GITTIMESTAMP
    static PATCHWORK_VERSION = "0.1a"
}