# Port to run on
port = 6008

# Not recommended to change this option
host = 0.0.0.0

# Default gamemode
# 0 = survival
# 1 = creative
# 3 = spectator
default_gamemode = creative

# OP by default
default_op = true

# If default_op = false then this works
# List of OP players
op_player_list = []

# MOTD
motd = "Brand new server"

# Allow modded clients to join
allowMods = false