// Integrated server worker. The singleplayer server (ServerRuntime plus the
// server world/player/entity modules) runs here so world ticking, chunk
// generation and save I/O never block the render thread. The browser page
// talks to this worker over postMessage; socket traffic is forwarded through
// the main thread's LoopbackServer (see IsomorphicWebSocket.js) as
// socket-connect / socket-message / socket-close messages.
import { Buffer } from '../../../../../../libraries/buffer.js';
import { readLongBE } from '../../server/binary.js';
import fs from '../fs/ServerFs.js';
import { initServer, onConnection, stopServer } from '../../server/ServerRuntime.js';
import * as serverWorld from '../../server/world.js';
import * as serverPlayers from '../../server/players.js';
import * as serverEntities from '../../server/entities.js';
import config from '../../server/config.js';
import path from '../../util/path.js';
import Long from '../../../../../../libraries/long.js';
import { serverNameForKey, parseServerConfig, gamemodeName } from './shared.js';

// worldKey is always 'w_<timestamp>_<random>'

const MODULE_DIR = new URL('.', import.meta.url).pathname;
const PROJECT_ROOT = path.join(MODULE_DIR, '..', '..', '..', '..', '..');
const WORLDS_DIR = path.join(PROJECT_ROOT, 'worlds');

const sockets = new Map(); // socketId -> server-side socket
let running = false;
let accepting = false;
let currentServerName = null;

function post(message, transfer) {
    if (transfer) {
        self.postMessage(message, transfer);
    } else {
        self.postMessage(message);
    }
}

// Server-side socket exposing the subset of the ws API ServerRuntime uses
// (on/off/send/close/readyState). All traffic is relayed over postMessage to
// the client socket held by the main thread's LoopbackServer.
function createServerSocket(socketId) {
    let readyState = 1;
    const listeners = {};

    const socket = {
        get readyState() {
            return readyState;
        },
        send(data) {
            if (readyState !== 1) return;
            if (typeof data === 'string') {
                post({ type: 'socket-message', socketId, data, isBinary: false });
                return;
            }
            let payload = data;
            if (ArrayBuffer.isView(data)) {
                payload = data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength);
            } else if (!(data instanceof ArrayBuffer)) {
                payload = new Uint8Array(data).buffer;
            }
            post({ type: 'socket-message', socketId, data: payload, isBinary: true }, [payload]);
        },
        close(code = 1000, reason = '') {
            if (readyState === 3) return;
            readyState = 3;
            post({ type: 'socket-close', socketId, code, reason });
        },
        on(event, cb) {
            listeners[event] = cb;
        },
        off(event, cb) {
            if (listeners[event] === cb) delete listeners[event];
        },
        _emit(event, ...args) {
            if (typeof listeners[event] === 'function') {
                listeners[event](...args);
            }
        },
        _terminate() {
            readyState = 3;
        },
    };

    return socket;
}

async function startServer(options) {
    if (running && currentServerName === serverNameForKey(options.worldKey)) {
        return;
    }
    if (running) {
        stopServerInternal();
    }

    await fs.ready();
    await fs.refresh();

    const serverName = serverNameForKey(options.worldKey);
    const serverDir = serverWorld.getWorldDir(serverName);
    if (!fs.existsSync(serverDir)) {
        fs.mkdirSync(serverDir, { recursive: true });
    }

    const seedLong = new Long(options.seedLow || 0, options.seedHigh || 0);
    const confPath = path.join(serverDir, 'serverconfig.conf');
    const existingConf = fs.existsSync(confPath) ? parseServerConfig(fs.readFileSync(confPath, 'utf8')) : null;
    const worldName = options.name || (existingConf && existingConf.name) || '';
    const confLines = [
        '# Auto-generated by the integrated server (singleplayer)',
        `default_gamemode=${options.gameMode || 'creative'}`,
        `worldType=${options.worldType || 'normal'}`,
        `seed=${seedLong.toString()}`,
        'allowMods=true',
    ];
    if (worldName) {
        confLines.push(`name=${worldName}`);
    }
    confLines.push('');
    fs.writeFileSync(confPath, confLines.join('\n'));

    config.reload(serverName);
    serverWorld.initWorld(serverName);

    // One-time migration of a legacy IndexedDB save into the server's file
    // layout. Runs between initWorld() (clears maps, creates the dir) and
    // initServer() (re-reads world_data.bin from disk).
    if (options.migrateData) {
        migrateLegacySave(options.migrateData, options.username);
    }

    initServer();
    accepting = true;
    currentServerName = serverName;
    running = true;
}

function stopServerInternal() {
    if (!running && !accepting) return;
    accepting = false;
    running = false;
    currentServerName = null;

    // Close any sockets still open so the client gets a clean 'close' event.
    for (const [socketId, socket] of sockets) {
        sockets.delete(socketId);
        socket._terminate();
        socket._emit('close', { code: 1000, reason: 'server stopped' });
        post({ type: 'socket-close', socketId, code: 1000, reason: 'server stopped' });
    }

    stopServer();
}

function listServerWorlds() {
    const worlds = [];
    if (!fs.existsSync(WORLDS_DIR)) {
        return worlds;
    }

    for (const entry of fs.readdirSync(WORLDS_DIR, { withFileTypes: true })) {
        if (!entry.isDirectory() || entry.name === 'main' || !/^[a-z0-9_]+$/.test(entry.name)) continue;

        const dir = path.join(WORLDS_DIR, entry.name);
        const confPath = path.join(dir, 'serverconfig.conf');
        const dataPath = path.join(dir, 'world_data.bin');
        if (!fs.existsSync(confPath) && !fs.existsSync(dataPath)) continue;

        const conf = fs.existsSync(confPath) ? parseServerConfig(fs.readFileSync(confPath, 'utf8')) : {};

        let seedLow = 0;
        let seedHigh = 0;
        if (conf.seed !== undefined && conf.seed !== null && conf.seed !== '') {
            try {
                const seedLong = Long.fromString(String(conf.seed));
                seedLow = seedLong.low;
                seedHigh = seedLong.high;
            } catch (e) {
                // Unparseable seed; leave as zero.
            }
        }

        let time = 0;
        if (fs.existsSync(dataPath)) {
            const data = fs.readFileSync(dataPath);
            if (data.length >= 8) {
                time = Number(readLongBE(data, 0));
            }
        }

        worlds.push({
            key: entry.name,
            name: conf.name || '',
            seedLow,
            seedHigh,
            worldType: conf.worldType || 'normal',
            gameMode: gamemodeName(conf.default_gamemode),
            time,
        });
    }
    return worlds;
}

// Remove a world's server files (world_data.bin, serverconfig.conf,
// players/...). The browser fs has no rmSync, so walk and unlink instead.
function deleteServerWorld(worldKey) {
    const serverName = serverNameForKey(worldKey);
    const dir = serverWorld.getWorldDir(serverName);
    const files = [];
    const walk = (d) => {
        for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
            const p = path.join(d, entry.name);
            if (entry.isDirectory()) walk(p);
            else files.push(p);
        }
    };
    try {
        if (fs.existsSync(dir)) walk(dir);
    } catch (e) {
        // Directory not readable; nothing to delete.
    }
    for (const file of files) {
        try {
            fs.unlinkSync(file);
        } catch (e) {
            // Ignore individual file failures.
        }
    }
}

// Push a legacy IndexedDB save into the server modules so it is re-written to
// the server's file layout on the next saveWorld().
function migrateLegacySave(saveData, username) {
    const chunks = saveData.chunks || {};
    for (const key in chunks) {
        const chunkData = chunks[key];
        if (!chunkData || !Array.isArray(chunkData.sections)) continue;
        const cx = chunkData.x;
        const cz = chunkData.z;
        for (let sy = 0; sy < chunkData.sections.length; sy++) {
            const section = chunkData.sections[sy];
            if (!section || !section.blocks) continue;
            for (const idxStr in section.blocks) {
                const idx = parseInt(idxStr, 10);
                const blockId = section.blocks[idx];
                if (!blockId) continue;
                const metadata = (section.blocksData && section.blocksData[idxStr]) || 0;
                serverWorld.addWorldChange(
                    cx * 16 + (idx & 15),
                    sy * 16 + ((idx >> 8) & 15),
                    cz * 16 + ((idx >> 4) & 15),
                    blockId,
                    metadata
                );
            }
        }
    }

    // Block inventories (chests / furnaces / signs)
    if (Array.isArray(saveData.blockInventories)) {
        for (const entry of saveData.blockInventories) {
            if (!entry || !entry.key) continue;
            serverWorld.setBlockInventory(entry.key, entry.state || entry.inventory || null);
        }
    }

    // World time
    if (typeof saveData.time === 'number') {
        serverWorld.setWorldTime(saveData.time);
    }

    // Dropped items (in-memory; regenerated from player drops if lost)
    if (Array.isArray(saveData.itemEntities)) {
        for (const item of saveData.itemEntities) {
            serverEntities.addItemEntity(
                item.blockId || 0,
                item.x || 0,
                item.y || 0,
                item.z || 0,
                item.motionX || 0,
                item.motionY || 0,
                item.motionZ || 0,
                0
            );
        }
    }

    // Player state -> players/<username>.json so the login handler restores it
    const gm = saveData.playerGameMode || {};
    serverPlayers.savePlayerData({
        username: username || 'Player',
        x: saveData.playerPos ? saveData.playerPos.x : undefined,
        y: saveData.playerPos ? saveData.playerPos.y : undefined,
        z: saveData.playerPos ? saveData.playerPos.z : undefined,
        yaw: saveData.playerRot ? saveData.playerRot.yaw : 0,
        pitch: saveData.playerRot ? saveData.playerRot.pitch : 0,
        isFlying: !!gm.flying,
        gamemode: gm.spectator ? 3 : gm.creative ? 1 : 0,
        health: typeof saveData.playerHealth === 'number' ? saveData.playerHealth : 20,
        inventory: saveData.playerInventory || [],
    });

    serverWorld.saveWorld();
}

async function handleMessage(msg) {
    if (!msg || typeof msg !== 'object') return;
    try {
        switch (msg.type) {
            case 'start':
                await startServer(msg);
                post({ type: 'ack', reqId: msg.reqId });
                break;

            case 'stop':
                stopServerInternal();
                // saveWorld() persists with fire-and-forget IndexedDB writes;
                // give them a beat to flush before the main thread reads the
                // world files again (e.g. the world-select list, deleteWorld).
                await new Promise((resolve) => setTimeout(resolve, 30));
                post({ type: 'ack', reqId: msg.reqId });
                break;

            case 'listWorlds':
                await fs.refresh();
                post({ type: 'result', reqId: msg.reqId, result: listServerWorlds() });
                break;

            case 'deleteWorld':
                await fs.refresh();
                deleteServerWorld(msg.worldKey);
                post({ type: 'result', reqId: msg.reqId, result: null });
                break;

            case 'socket-connect': {
                if (!accepting) {
                    post({ type: 'socket-close', socketId: msg.socketId, code: 1006, reason: 'server not running' });
                    break;
                }
                const socket = createServerSocket(msg.socketId);
                sockets.set(msg.socketId, socket);
                onConnection(socket);
                post({ type: 'socket-open', socketId: msg.socketId });
                break;
            }

            case 'socket-message': {
                const socket = sockets.get(msg.socketId);
                if (!socket) break;
                const data = msg.isBinary ? Buffer.from(new Uint8Array(msg.data)) : msg.data;
                socket._emit('message', data, !!msg.isBinary);
                break;
            }

            case 'socket-close': {
                const socket = sockets.get(msg.socketId);
                if (!socket) break;
                sockets.delete(msg.socketId);
                socket._terminate();
                socket._emit('close', { code: msg.code || 1000, reason: msg.reason || '' });
                break;
            }

            default:
                break;
        }
    } catch (err) {
        console.error('[IntegratedServer] worker handler error:', err);
        post({ type: 'error', reqId: msg.reqId, message: (err && err.message) || String(err) });
    }
}

self.onmessage = (e) => {
    handleMessage(e.data);
};
